import {
  LogBase,
  PKAnalysisError,
  PKAnalysisOutcome,
  PKAnalysisSuccess,
  PKCalculationStep,
  PKDataPoint,
  PKInterpretation,
  PKObservation,
  PKPredictionRow,
  PKRegressionResult,
  PKUnits,
  PKWarning,
  RegressionStatistics,
  TerminalPhase,
  TrapezoidalAUC,
} from '../../types';
import { calculateSimpleLinearRegression } from '../statistics/linearRegression';
import {
  calculateAUC,
  calculateC0FromIntercept,
  calculateClearance,
  calculateHalfLife,
  calculateKFromLnSlope,
  calculateKFromLog10Slope,
  calculateVd,
} from './elimination';
import { analyzePKData } from './pkRegression';
import { buildPKInterpretation } from './pkInterpretation';
import { composeTrapezoidalAUC } from './trapezoidalAUC';
import { selectTerminalPhase, TerminalPhaseStrategy } from './terminalPhase';

/**
 * Phase 4 — Pharmacokinetics Analysis Engine (spec §1, §3, §5-§8).
 *
 * This is the canonical PK analysis entry point. It composes:
 *   - Phase 2 `analyzePKData` (slope, intercept, k, t½, C₀, theoretical AUC)
 *   - Phase 2 OLS engine (called via analyzePKData, no duplication)
 *   - Phase 4 trapezoidal AUC (spec §13, §14)
 *   - Phase 4 terminal-phase selection (spec §15)
 *   - Phase 4 per-observation predictions and residuals (spec §11, §12)
 *   - Phase 4 calculation trace generated by the domain layer (spec §17)
 *   - Phase 4 educational interpretation (spec §19)
 *
 * Spec §3 architecture:
 *
 *   UI → PK Analysis Service (this module) → Regression/Transformation → Pure Math
 *
 * Spec §6: "Do NOT implement a second independent OLS algorithm inside the
 * PK module." This engine calls `analyzePKData` (which calls
 * `calculateSimpleLinearRegression`) — no duplicate regression math.
 *
 * Spec §34: NO rounding inside the engine. All numeric fields preserve
 * full IEEE-754 double precision. Formatting is the presentation layer's
 * responsibility.
 */

export interface AnalyzePKOptions {
  logBase?: LogBase;
  units?: PKUnits;
  dose?: number;
  confidenceLevel?: number;
  terminalPhaseStrategy?: TerminalPhaseStrategy;
  /** Override the terminal-phase minimum point count (default 3). */
  minTerminalPoints?: number;
}

/**
 * Runs a complete first-order elimination PK analysis.
 *
 * Workflow (spec §5, §6):
 *   1. Validate input (lengths, finiteness, positivity for log transform)
 *   2. Select terminal phase (default: 'all-points' for clean educational data)
 *   3. Delegate to Phase 2 `analyzePKData` for slope/intercept/k/t½/C₀/AUC_theoretical
 *   4. Compute trapezoidal AUC + extrapolation (Phase 4)
 *   5. Build per-observation predictions and residuals
 *   6. Generate calculation trace (Phase 4)
 *   7. Generate interpretation narratives (Phase 4)
 *   8. Collect warnings (Phase 4)
 */
export function analyzeFirstOrderElimination(
  data: { id?: string; time: number; concentration: number }[],
  options: AnalyzePKOptions = {}
): PKAnalysisOutcome {
  const {
    logBase = 'ln',
    units = { time: 'h', concentration: 'mg/L', dose: 'mg' },
    dose,
    confidenceLevel = 0.95,
    terminalPhaseStrategy = 'all-points',
    minTerminalPoints = 3,
  } = options;

  // ----------------------------------------------------------------
  // Step 1: Input validation (spec §5, §22, §29)
  // ----------------------------------------------------------------
  if (!data || data.length < 2) {
    return errorOutcome(
      'INSUFFICIENT_DATA',
      `At least 2 valid time-concentration pairs are required to compute PK elimination parameters. Received ${data?.length ?? 0}.`
    );
  }

  // Check for non-finite values and non-positive concentrations
  const invalidRows: NonNullable<PKAnalysisError['invalidRows']> = [];
  for (let i = 0; i < data.length; i++) {
    const pt = data[i];
    if (!isFinite(pt.time) || !isFinite(pt.concentration)) {
      invalidRows.push({
        row: i + 1,
        time: pt.time,
        concentration: pt.concentration,
        reason: `Non-finite value (time=${pt.time}, concentration=${pt.concentration})`,
      });
    } else if (pt.concentration <= 0) {
      invalidRows.push({
        row: i + 1,
        time: pt.time,
        concentration: pt.concentration,
        reason: `Concentration must be > 0 for ${logBase} transformation (received ${pt.concentration})`,
      });
    }
  }
  if (invalidRows.length > 0) {
    return errorOutcome(
      invalidRows[0].reason.includes('Non-finite') ? 'NON_FINITE_VALUE' : 'NON_POSITIVE_CONCENTRATION',
      `PK analysis cannot be calculated because ${invalidRows.length} observation(s) are invalid.\n\n` +
        `Invalid observations:\n` +
        invalidRows.slice(0, 10).map((r) => `  Row ${r.row}: ${r.reason}`).join('\n') +
        (invalidRows.length > 10 ? `\n  … and ${invalidRows.length - 10} more` : ''),
      invalidRows
    );
  }

  // Filter to valid observations (defensive — should be all of them by now)
  const validData: PKObservation[] = data
    .filter((pt) => isFinite(pt.time) && isFinite(pt.concentration) && pt.concentration > 0)
    .map((pt, i) => ({
      id: pt.id || `pt-${i + 1}`,
      time: pt.time,
      concentration: pt.concentration,
    }));

  if (validData.length < 2) {
    return errorOutcome(
      'INSUFFICIENT_DATA',
      'After filtering invalid observations, fewer than 2 valid pairs remain.'
    );
  }

  // Check for duplicate time values (non-fatal warning, but flag it)
  const timeSet = new Set(validData.map((p) => p.time));
  const hasDuplicateTimes = timeSet.size < validData.length;
  const hasZeroTimeVariance = timeSet.size === 1;

  if (hasZeroTimeVariance) {
    return errorOutcome(
      'ZERO_TIME_VARIANCE',
      `All time values are identical (${validData[0].time}). Regression requires at least 2 distinct time points.`
    );
  }

  // ----------------------------------------------------------------
  // Step 2: Terminal-phase selection (spec §15)
  // ----------------------------------------------------------------
  const terminalPhase: TerminalPhase = selectTerminalPhase(validData, {
    strategy: terminalPhaseStrategy,
    minPoints: minTerminalPoints,
    logBase,
  });

  // ----------------------------------------------------------------
  // Step 3: Delegate to Phase 2 analyzePKData for the regression
  // ----------------------------------------------------------------
  // Convert validData to PKDataPoint for backward compatibility with
  // the Phase 2 API.
  const pkDataPoints: PKDataPoint[] = validData.map((p) => ({
    id: p.id,
    time: p.time,
    concentration: p.concentration,
  }));

  const phase2Result = analyzePKData(
    pkDataPoints,
    logBase,
    units,
    dose && dose > 0 ? dose : undefined
  );

  if (phase2Result.status === 'error') {
    return errorOutcome(
      'INVALID_REGRESSION',
      `Underlying OLS regression failed: ${phase2Result.error.message}`
    );
  }

  const regression: PKRegressionResult = phase2Result.regression;
  const underlyingReg = phase2Result.underlyingRegression;
  if (underlyingReg.status !== 'success') {
    return errorOutcome(
      'INVALID_REGRESSION',
      'Underlying OLS regression returned an unexpected error state.'
    );
  }
  const olsStatistics: RegressionStatistics = underlyingReg.stats;

  // ----------------------------------------------------------------
  // Step 4: Trapezoidal AUC + extrapolation (Phase 4, spec §13, §14)
  // ----------------------------------------------------------------
  const aucTheoretical = calculateAUC(regression.estimatedC0, regression.eliminationRateConstant);
  const trapezoidalAUC: TrapezoidalAUC = composeTrapezoidalAUC(
    validData.map((p) => ({ time: p.time, concentration: p.concentration })),
    regression.eliminationRateConstant,
    regression.estimatedC0,
    aucTheoretical
  );

  // ----------------------------------------------------------------
  // Step 5: Per-observation predictions and residuals (spec §11, §12)
  // ----------------------------------------------------------------
  const selectedSet = new Set(terminalPhase.selectedIndices);
  const predictions: PKPredictionRow[] = validData.map((pt, idx) => {
    const zObserved =
      logBase === 'ln' ? Math.log(pt.concentration) : Math.log10(pt.concentration);
    const zPredicted = regression.intercept + regression.slope * pt.time;
    const yPredicted =
      logBase === 'ln' ? Math.exp(zPredicted) : Math.pow(10, zPredicted);
    return {
      id: pt.id,
      time: pt.time,
      concentrationObserved: pt.concentration,
      concentrationTransformed: zObserved,
      concentrationPredictedTransformed: zPredicted,
      concentrationPredicted: yPredicted,
      residualTransformed: zObserved - zPredicted,
      residualOriginal: pt.concentration - yPredicted,
      inTerminalPhase: selectedSet.has(idx),
    };
  });

  // ----------------------------------------------------------------
  // Step 6: Calculation trace (spec §17)
  // ----------------------------------------------------------------
  const calculationTrace = buildCalculationTrace(
    logBase,
    regression,
    olsStatistics,
    trapezoidalAUC,
    units
  );

  // ----------------------------------------------------------------
  // Step 7: Interpretation narratives (spec §19)
  // ----------------------------------------------------------------
  const interpretation: PKInterpretation = buildPKInterpretation(
    regression,
    trapezoidalAUC,
    units
  );

  // ----------------------------------------------------------------
  // Step 8: Warnings (spec §22, §29)
  // ----------------------------------------------------------------
  const warnings: PKWarning[] = [];
  if (regression.slope >= 0) {
    warnings.push({
      code: 'POSITIVE_SLOPE',
      message:
        `The fitted slope is positive or zero (slope = ${regression.slope}). ` +
        `In first-order elimination, concentration decreases over time, so the slope on ` +
        `the log scale should be negative. Verify the data or the time ordering.`,
      severity: 'warning',
    });
  }
  if (regression.rSquared < 0.9 && regression.rSquared >= 0) {
    warnings.push({
      code: 'POOR_TERMINAL_FIT',
      message:
        `R² = ${regression.rSquared.toFixed(4)} on the log scale is below 0.90. ` +
        `The log-linear fit is weak — the data may not follow mono-exponential elimination, ` +
        `or the terminal-phase point selection may need adjustment.`,
      severity: 'caution',
    });
  }
  if (
    !trapezoidalAUC.extrapolationSuppressed &&
    isFinite(trapezoidalAUC.extrapFraction) &&
    trapezoidalAUC.extrapFraction > 0.2
  ) {
    warnings.push({
      code: 'HIGH_EXTRAPOLATION_FRACTION',
      message:
        `Extrapolated AUC accounts for ${(trapezoidalAUC.extrapFraction * 100).toFixed(1)}% ` +
        `of AUC_total. Values above 20% suggest the sampling window is too short and the ` +
        `AUC_total estimate is highly model-dependent.`,
      severity: 'caution',
    });
  }
  if (terminalPhase.pointCount < 3) {
    warnings.push({
      code: 'FEW_TERMINAL_POINTS',
      message:
        `Only ${terminalPhase.pointCount} point(s) were used in the terminal-phase regression. ` +
        `Slope estimates from fewer than 3 points are statistically unstable.`,
      severity: 'caution',
    });
  }
  if (hasDuplicateTimes) {
    warnings.push({
      code: 'DUPLICATE_TIMES',
      message:
        `The dataset contains duplicate time values. Regression will treat each as a ` +
        `separate observation, which may over-weight certain time points.`,
      severity: 'info',
    });
  }
  // Check for non-monotonic time (after sorting, the original order had decreases)
  const originalTimes = data.map((p) => p.time);
  let isMonotonic = true;
  for (let i = 1; i < originalTimes.length; i++) {
    if (originalTimes[i] < originalTimes[i - 1]) {
      isMonotonic = false;
      break;
    }
  }
  if (!isMonotonic) {
    warnings.push({
      code: 'NON_MONOTONIC_TIME',
      message:
        `Time values were not in ascending order in the input data. The analysis uses ` +
        `time-sorted observations, but you may want to verify the original data entry.`,
      severity: 'info',
    });
  }

  // ----------------------------------------------------------------
  // Step 9: Assemble final result
  // ----------------------------------------------------------------
  const success: PKAnalysisSuccess = {
    status: 'success',
    logBase,
    rawData: validData,
    regression,
    olsStatistics,
    trapezoidalAUC,
    terminalPhase,
    predictions,
    calculationTrace,
    interpretation,
    warnings,
    confidenceLevel,
    units,
    dose: dose && dose > 0 ? dose : undefined,
  };

  return success;
}

// ===========================================================================
// Helper: build the PK calculation trace (spec §17)
// ===========================================================================

function buildCalculationTrace(
  logBase: LogBase,
  regression: PKRegressionResult,
  ols: RegressionStatistics,
  auc: TrapezoidalAUC,
  units: PKUnits
): PKCalculationStep[] {
  const steps: PKCalculationStep[] = [];
  const logNotation = logBase === 'ln' ? '\\ln' : '\\log_{10}';
  const backNotation = logBase === 'ln' ? 'e' : '10';
  const { slope, intercept, eliminationRateConstant: k, halfLife, estimatedC0: c0 } = regression;

  // Step 1: Transform
  steps.push({
    step: 1,
    title: `Transform C → z = ${logNotation}(C)`,
    description:
      `Apply the ${logBase === 'ln' ? 'natural' : 'common'} logarithm to each observed concentration. ` +
      `This linearizes the exponential decay: if C(t) = C₀·e^(−kt), then ${logNotation}(C) = ${logNotation}(C₀) − kt.`,
    formulaLatex: `z_i = ${logNotation}(C_i)`,
    result: `Transformed ${ols.n} concentration values to the ${logBase} scale.`,
  });

  // Step 2: Linear regression
  steps.push({
    step: 2,
    title: `Fit OLS Regression: z = a + b·t`,
    description:
      `Use ordinary least squares (Phase 2 engine) to fit a straight line to (t, z). ` +
      `The line minimizes the sum of squared vertical residuals on the transformed scale.`,
    formulaLatex: `\\hat{z}_i = a + b \\cdot t_i, \\quad b = \\frac{S_{tz}}{S_{tt}}, \\quad a = \\bar{z} - b \\bar{t}`,
    result: `Slope b = ${slope}, intercept a = ${intercept}, R² = ${regression.rSquared}.`,
  });

  // Step 3: Slope
  steps.push({
    step: 3,
    title: 'Extract the Slope (b)',
    description:
      `The slope describes the rate of change of ${logNotation}(C) per unit time. ` +
      `For first-order elimination, this slope is negative (concentration decays).`,
    formulaLatex: `b = \\frac{S_{tz}}{S_{tt}} = ${slope} \\text{ ${units.time}}^{-1}`,
    result: `b = ${slope} ${units.time}⁻¹`,
  });

  // Step 4: k = -slope (or -slope × ln10)
  steps.push({
    step: 4,
    title: `Derive Elimination Rate Constant (k)`,
    description:
      logBase === 'ln'
        ? `On the ln scale, slope = −k, so k = −slope directly.`
        : `On the log10 scale, slope = −k/ln(10), so k = −slope × ln(10) ≈ −2.303 × slope.`,
    formulaLatex:
      logBase === 'ln'
        ? `k = -b = -(${slope}) = ${k} \\text{ ${units.time}}^{-1}`
        : `k = -b \\cdot \\ln(10) = -(${slope}) \\times \\ln(10) = ${k} \\text{ ${units.time}}^{-1}`,
    result: `k = ${k} ${units.time}⁻¹`,
  });

  // Step 5: t½ = ln(2)/k
  steps.push({
    step: 5,
    title: 'Calculate Half-Life (t½)',
    description:
      `Half-life is the time required for concentration to decrease by 50% under first-order kinetics. ` +
      `It is constant (independent of dose) and inversely proportional to k.`,
    formulaLatex:
      isFinite(halfLife) && halfLife > 0
        ? `t_{1/2} = \\frac{\\ln(2)}{k} = \\frac{0.69315}{${k}} = ${halfLife} \\text{ ${units.time}}`
        : `t_{1/2} = \\frac{\\ln(2)}{k} \\quad \\text{(undefined: k ≤ 0)}`,
    result:
      isFinite(halfLife) && halfLife > 0
        ? `t½ = ${halfLife} ${units.time}`
        : `t½ undefined (k = ${k} is not positive)`,
  });

  // Step 6: C₀ = exp(intercept) or 10^intercept
  steps.push({
    step: 6,
    title: 'Estimate Initial Concentration (C₀)',
    description:
      `C₀ is the model's prediction at t = 0, recovered by back-transforming the intercept. ` +
      `This is an extrapolation, not necessarily an observed measurement.`,
    formulaLatex:
      `C_0 = ${backNotation}^{a} = ${backNotation}^{${intercept}} = ${c0} \\text{ ${units.concentration}}`,
    result: `C₀ = ${c0} ${units.concentration}`,
  });

  // Step 7: AUC
  steps.push({
    step: 7,
    title: 'Compute AUC (Trapezoidal + Extrapolation)',
    description:
      `AUC_last is computed by the linear trapezoidal rule over observed data. ` +
      `AUC_extra = C_last / k extrapolates to infinity assuming first-order elimination continues. ` +
      `AUC_total = AUC_last + AUC_extra. The theoretical model-based AUC = C₀/k is shown for comparison.`,
    formulaLatex:
      `\\text{AUC}_{last} = \\sum_{i=1}^{n-1} \\frac{C_i + C_{i+1}}{2}(t_{i+1} - t_i) = ${auc.aucLast} \\\\[4pt] ` +
      `\\text{AUC}_{extra} = \\frac{C_{last}}{k} = ${auc.aucExtra} \\\\[4pt] ` +
      `\\text{AUC}_{total} = \\text{AUC}_{last} + \\text{AUC}_{extra} = ${auc.aucTotal} \\\\[4pt] ` +
      `\\text{AUC}_{theoretical} = \\frac{C_0}{k} = ${auc.aucTheoretical}`,
    result: `AUC_last = ${auc.aucLast} ${units.concentration}·${units.time}` +
      (auc.extrapolationSuppressed
        ? ` (extrapolation suppressed)`
        : `, AUC_total = ${auc.aucTotal} ${units.concentration}·${units.time}`),
  });

  return steps;
}

// ===========================================================================
// Helper: construct error outcome
// ===========================================================================

function errorOutcome(
  type: PKAnalysisError['type'],
  message: string,
  invalidRows?: PKAnalysisError['invalidRows']
): PKAnalysisError {
  return { status: 'error', type, message, invalidRows };
}

// ===========================================================================
// Public utility: predict concentration at a new time (spec §11)
// ===========================================================================

/**
 * Predicts concentration at a new time t using the fitted first-order model.
 *
 * For ln model:   ln(C_pred) = intercept + slope·t  →  C_pred = exp(intercept + slope·t)
 * For log10 model: log10(C_pred) = intercept + slope·t  →  C_pred = 10^(intercept + slope·t)
 *
 * Spec §11: prediction functionality should be reusable.
 * Spec §34: no rounding.
 */
export function predictConcentration(
  time: number,
  regression: { intercept: number; slope: number; logBase: LogBase }
): number {
  const z = regression.intercept + regression.slope * time;
  return regression.logBase === 'ln' ? Math.exp(z) : Math.pow(10, z);
}

// ===========================================================================
// Public utility: recover Phase 2 k-derivation formulas for educational use
// ===========================================================================

/**
 * Educational helper: returns the formula string for k derivation given the log base.
 * Used by the UI to display the formula without hardcoding it in JSX (spec §3).
 */
export function kDerivationFormula(logBase: LogBase): string {
  return logBase === 'ln'
    ? 'k = -\\text{slope}'
    : 'k = -\\text{slope} \\cdot \\ln(10) \\approx -2.303 \\cdot \\text{slope}';
}

/**
 * Educational helper: returns the formula string for C₀ derivation.
 */
export function c0DerivationFormula(logBase: LogBase): string {
  return logBase === 'ln'
    ? 'C_0 = e^{\\text{intercept}}'
    : 'C_0 = 10^{\\text{intercept}}';
}
